name: Web Scraping and Notification

on:
  push:
      branches: [ master ]
  schedule: 
    - cron: "* 1 * * *"  #定时任务 用于9点定时触发 

jobs:
  scrape_and_notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          node-version: 18

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install dependencies
        run: yarn install

      # - name: Run the scraper and generator # name后面的是当前任务的描述, 不需要管
          #run: node scraper.js # 替换为您的爬虫脚本的文件名

      - name: Build with VitePress
        run: yarn docs:build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: docs/.vitepress/dist
          

      - name: Deploy to GitHub Pages1
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACCESS_TOKEN }}
          publish_dir: ./docs/.vitepress/dist

      - name: Show Deployed URL
        run: |
          echo "Deployed Website URL: https://zhunnlin.github.io/studyProject/"

      - name: Send email notification
        run: npm run start # 替换为发送邮件的脚本命令或代码
        env:
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_SEND_TO: ${{ secrets.SMTP_SEND_TO }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
